version: '3.8'

services:
  restconf-server:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/.well-known/host-meta"]
      interval: 30s
      timeout: 10s
      retries: 3
